name: Code Quality Assurance

on:
    push:
        branches: [main]
        paths:
            - 'public/**'
            - 'src/**'
            - '**/*.json'
            - '**/*.js'
            - '**/*.ts'
            - '**/*.tsx'
            - '**/*.jsx'
            - '**/*.css'
            - '**/*.scss'
            - '**/*.html'
            - '.github/workflows/code-qa.yaml'
    pull_request:
        branches: [main]
        paths:
            - 'public/**'
            - 'src/**'
            - '**/*.json'
            - '**/*.js'
            - '**/*.ts'
            - '**/*.tsx'
            - '**/*.jsx'
            - '**/*.css'
            - '**/*.scss'
            - '**/*.html'
            - '.github/workflows/code-qa.yaml'

permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache Node.js modules
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Check installs
              run: npm ci
            - name: Quality check - prettier
              run: npm run prettier:check
            - name: Quality check - eslint
              run: npm run eslint:check
            - name: Quality check - type check
              run: npm run tsc
            - name: Quality check - unit tests
              run: npm run test:jest
            - name: Quality check - cypress e2e tests
              run: npm run test:cypress:e2e
            - name: Build check
              run: npm run build
